# -*- coding:utf8 -*-
import pymongo

ip = '172.16.9.146'
#ip = '119.254.86.74'
web_ip = 'opscn.dolphin-browser.com/resources/desktops/icon/'
conn = pymongo.Connection(ip)
db = conn['dolphinop']
data = {
        'id':1,
        'source':'ofw',
        'pname':'com.dolphin.browser.cn',
        'operators':['00', '01', '02', '03', 'other_condition',],
        'data':[{'sid':1,
                 'its':[
                        {'id':7,
                         'ttl':'精彩娱乐',
                         'p':9,
                         'its':[{'id':1,
                                 'ttl':'段子',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, 'duanzi.png'),
                                 'url':'http://reader.dolphin-browser.com/#ch2454',
                                 'txt':'该图标的tips',
                                 },
                                {'id':2,
                                 'ttl':'冷笑话',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, 'lengxiaohua.png'),
                                 'url':'http://m.lengxiaohua.com/',
                                 'txt':'该图标的tips',
                                 },
                                {'id':3,
                                 'ttl':'娱乐花边',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, 'yulehuabian.png'),
                                 'url':'http://reader.dolphin-browser.com/#ch2417',
                                 'txt':'该图标的tips',
                                 },
                                {'id':4,
                                 'ttl':'搞笑漫画',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, 'gaoxiaomanhua.png'),
                                 'url':'http://manhua.weibo.cn/',
                                 'txt':'该图标的tips',
                                 },
                                {'id':5,
                                 'ttl':'两性',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, 'liangxing.png'),
                                 'url':'http://reader.dolphin-browser.com/#ch2433',
                                 'txt':'该图标的tips',
                                 },
                                {'id':6,
                                 'ttl':'福利社',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, 'fulishe.png'),
                                 'url':'http://danhuaer.com/',
                                 'txt':'该图标的tips',
                                 },
                                ]
                         },
                        {'id':8,
                         'ttl':'百度一下',
                         'p':2,
                         'd':True,
                         'ico':'http://%s%s' % (web_ip, 'baidu.png'),
                         'url':'http://m.baidu.com/?from=1000406a',
                         'txt':'该图标的tips',
                         },
                        {'id':9,
                         'ttl':'二维码',
                         'p':4,
                         'd':False,
                         'ico':'http://%s%s' % (web_ip, 'erweima.png'),
                         'url':'dolphin://qrcode',
                         'txt':'该图标的tips',
                         },
                        {'id':10,
                         'ttl':'美女辣图',
                         'p':8,
                         'd':True,
                         'ico':'http://%s%s' % (web_ip, 'meinvlatu.png'),
                         'url':'http://latu.3g.cn',
                         'txt':'该图标的tips',
                         },
                        {'id':11,
                         'ttl':'小说阅读',
                         'p':10,
                         'its':[{'id':12,
                                 'ttl':'移动书城',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, 'shucheng.png'),
                                 'url':'http://wap.cmread.com',
                                 'txt':'该图标的tips',
                                 },
                                {'id':13,
                                 'ttl':'起点中文',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, 'qidian.png'),
                                 'url':'http://m.qidian.com',
                                 'txt':'该图标的tips',
                                 },
                                {'id':14,
                                 'ttl':'纵横网',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, 'zongheng.png'),
                                 'url':'http://wap.zongheng.com',
                                 'txt':'该图标的tips',
                                 },
                                {'id':15,
                                 'ttl':'潇湘书院',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, 'xiaoxiang.png'),
                                 'url':'http://m.xxsy.net',
                                 'txt':'该图标的tips',
                                 },
                                {'id':16,
                                 'ttl':'红袖添香',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, 'hongxiu.png'),
                                 'url':'http://wap.hongxiu.com',
                                 'txt':'该图标的tips',
                                 },
                                {'id':17,
                                 'ttl':'1001页',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, '1001p.png'),
                                 'url':'http://m.1001p.com/',
                                 'txt':'该图标的tips',
                                 },
                                {'id':18,
                                 'ttl':'17k',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, '17k.png'),
                                 'url':'http://wap.17kts.com',
                                 'txt':'该图标的tips',
                                 },
                                {'id':19,
                                 'ttl':'幻剑书盟',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, 'shumeng.png'),
                                 'url':'http://wap.hjsm.tom.com/',
                                 'txt':'该图标的tips',
                                 },
                                ]
                         },
                        {'id':20,
                         'ttl':'优酷视频',
                         'p':5,
                         'd':True,
                         'ico':'http://%s%s' % (web_ip, 'youku.png'),
                         'url':'http://m.youku.com',
                         'txt':'该图标的tips',
                         },
                        {'id':21,
                         'ttl':'淘宝热卖',
                         'p':7,
                         'd':True,
                         'ico':'http://%s%s' % (web_ip, 'taobao.png'),
                         'url':'http://m.taobao.com',
                         'txt':'该图标的tips',
                         },
                        {'id':22,
                         'ttl':'凤凰新闻',
                         'p':1,
                         'd':True,
                         'ico':'http://%s%s' % (web_ip, 'ifeng.png'),
                         'url':'http://3g.ifeng.com/',
                         'txt':'该图标的tips',
                         },
                        {'id':23,
                         'ttl':'人气论坛',
                         'p':3,
                         'd':True,
                         'ico':'http://%s%s' % (web_ip, 'luntan.png'),
                         'url':'http://forum.dolphin-browser.com/',
                         'txt':'该图标的tips',
                         },
                        {'id':24,
                         'ttl':'微博',
                         'p':6,
                         'd':True,
                         'ico':'http://%s%s' % (web_ip, 'weibo.png'),
                         'url':'http://m.weibo.cn',
                         'txt':'该图标的tips',
                         },
                        ],
                 },
                {'sid':2,
                 'its':[
                        {'id':25,
                         'ttl':'下载管理',
                         'p':4,
                         'd':False,
                         'ico':'http://%s%s' % (web_ip, 'downloads.png'),
                         'url':'dolphin://downloads',
                         'txt':'该图标的tips',
                         },
                        {'id':26,
                         'ttl':'收藏夹',
                         'p':1,
                         'd':False,
                         'ico':'http://%s%s' % (web_ip, 'bookmarks.png'),
                         'url':'dolphin://bookmarks',
                         'txt':'该图标的tips',
                         },
                        {'id':27,
                         'ttl':'生活贴士',
                         'p':3,
                         'its':[{'id':28,
                                 'ttl':'开奖公告',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, 'kaijianggonggao.png'),
                                 'url':'http://m.caipiaokong.com',
                                 'txt':'该图标的tips',
                                 },
                                {'id':29,
                                 'ttl':'天气预报',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, 'tianqiyubao.png'),
                                 'url':'http://m.hao123.com/a/tianqi',
                                 'txt':'该图标的tips',
                                 },
                                {'id':30,
                                 'ttl':'列车查询',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, 'liechechaxun.png'),
                                 'url':'http://touch.qunar.com/train.jsp',
                                 'txt':'该图标的tips',
                                 },
                                {'id':31,
                                 'ttl':'订车票',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, 'huochepiaoyuding.png'),
                                 'url':'http://m.tieyou.com',
                                 'txt':'该图标的tips',
                                 },
                                {'id':32,
                                 'ttl':'快递查询',
                                 'd':True,
                                 'ico':'http://%s%s' % (web_ip, 'kuaidichaxun.png'),
                                 'url':'http://m.46644.com',
                                 'txt':'该图标的tips',
                                 },
                                ]
                         },
                        {'id':33,
                         'ttl':'浏览工具',
                         'p':2,
                         'its':[{'id':34,
                                 'ttl':'一键清理',
                                 'd':False,
                                 'ico':'http://%s%s' % (web_ip, 'cleardata.png'),
                                 'url':'dolphin://datas',
                                 'txt':'该图标的tips',
                                 },
                                {'id':35,
                                 'ttl':'云备份',
                                 'd':False,
                                 'ico':'http://%s%s' % (web_ip, 'cloudsync.png'),
                                 'url':'dolphin://cloud',
                                 'txt':'该图标的tips',
                                 },
                                {'id':36,
                                 'ttl':'安全选项',
                                 'd':False,
                                 'ico':'http://%s%s' % (web_ip, 'securityoption.png'),
                                 'url':'dolphin://security',
                                 'txt':'该图标的tips',
                                 },
                                {'id':37,
                                 'ttl':'用户反馈',
                                 'd':False,
                                 'ico':'http://%s%s' % (web_ip, 'feedback.png'),
                                 'url':'http://cn.dolphin-browser.com/feedback.htm?os=android&pn=com.dolphin.browser.cn&vn=91&src=ofw',
                                 'txt':'该图标的tips',
                                 },
                                ]
                         },
                        {'id':38,
                         'ttl':'设置',
                         'p':5,
                         'd':False,
                         'ico':'http://%s%s' % (web_ip, 'settings.png'),
                         'url':'dolphin://settings',
                         'txt':'该图标的tips',
                         },
                        {'id':39,
                         'ttl':'皮肤',
                         'p':6,
                         'd':False,
                         'ico':'http://%s%s' % (web_ip, 'theme.png'),
                         'url':'dolphin://theme',
                         'txt':'该图标的tips',
                         },
                    ]
               },
          ]
      }
db.desktops.remove()
db.desktops.insert(data)
