OK = 0

UNKNOWN_ERROR = 1
HTTPS_REQUIRED = 2
PARAM_REQUIRED = 3
DATA_ERROR = 4
DB_ERROR = 5
PERMISSION_DENY = 6
AUTH_ERROR = 7
PASSWORD_UNMATCH = 8
SAVE_ERROR = 9
PARAM_ERROR = 10
METHOD_ERROR = 11
IO_ERROR = 12
CONTENT_NOT_FOUND = 13
